#
# tests/Makefile - Run all tests
#
# This work is licensed under the terms of the MIT License.
# A copy of the license can be found in the file LICENSE.MIT
#

#
# @@@ Our test cases are scattered over several different frameworks, Should
# try to unify them, at least a little.
#

all:
	./pages.sh
	./tsort.sh
	./move.sh
	./rmt.sh
	./db.sh
